name: 'Build and release'

on: workflow_dispatch

jobs:
  build:
    name: 'Build the project'
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.tag.outputs.tag }}
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3
        with:
          ref: master
      - name: 'Set up Java'
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'
      - name: 'Build native executables'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: linkReleaseExecutableMacosX64 linkReleaseExecutableMingwX64 linkReleaseExecutableLinuxX64
      - name: 'Build shadow jar'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar
      - name: 'Upload Jar Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./build/libs/*-all.jar
      - name: 'Upload macosX64'
        uses: actions/upload-artifact@v2
        with:
          name: artifacts1
          path: ./build/bin/macosX64/releaseExecutable/google-auth-decode-macosX64.kexe
      - name: 'Upload MingwX64'
        uses: actions/upload-artifact@v2
        with:
          name: artifacts2
          path: ./build/bin/MingwX64/releaseExecutable/google-auth-decode-MingwX64.kexe
      - name: 'Upload LinuxX64'
        uses: actions/upload-artifact@v2
        with:
          name: artifacts3
          path: ./build/bin/LinuxX64/releaseExecutable/google-auth-decode-LinuxX64.kexe
      - name: 'export version number'
        id: tag
        run: ./gradlew properties -q | grep "version:" | awk '{ print "::set-output name=tag::"$2 }'

  release-content:
    name: 'Create GitHub Release'
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Download Jar Artifact'
        uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: 'Download Jar Artifact'
        uses: actions/download-artifact@v2
        with:
          name: artifacts1
      - name: 'Download Jar Artifact'
        uses: actions/download-artifact@v2
        with:
          name: artifacts2
      - name: 'Download Jar Artifact'
        uses: actions/download-artifact@v2
        with:
          name: artifacts3
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./*
          tag_name: ${{needs.build.outputs.tag-name}}
          name: version v${{needs.build.outputs.tag-name}}