name: 'Release'

on: workflow_dispatch

jobs:
  release-content:
    name: 'Create GitHub Release'
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 'Download Jar Artifact'
        uses: actions/download-artifact@v2
        with:
          name: artifact
      - name: 'Create GitHub Release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./*
          tag_name: ${{needs.build.outputs.tag-name}}
          name: version v${{needs.build.outputs.tag-name}}